# Generated by Django 4.2.1 on 2023-06-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('class_lit', models.CharField(max_length=2, verbose_name='Lit')),
                ('class_num', models.IntegerField(max_length=2, verbose_name='Номер класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, verbose_name='Username')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('password', models.CharField(verbose_name='Пароль')),
                ('email', models.CharField(verbose_name='Почта')),
                ('access_t', models.BooleanField(verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
    ]
