# Generated by Django 4.2.1 on 2023-06-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obj_shablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=25, verbose_name='Theme')),
                ('name', models.CharField(max_length=20, verbose_name='Name_obj')),
                ('min_value', models.IntegerField(default=1)),
                ('max_value', models.IntegerField(default=100)),
                ('unit1', models.CharField(max_length=15, verbose_name='Unit1')),
                ('max_s', models.IntegerField(default=500)),
                ('unit2', models.CharField(max_length=20, verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Шаблон задания',
                'verbose_name_plural': 'Шаблоны заданий',
            },
        ),
        migrations.CreateModel(
            name='Task_shablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=25, verbose_name='Theme')),
                ('task', models.CharField(max_length=350, verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Шаблон задания',
                'verbose_name_plural': 'Шаблоны заданий',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Info_about_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.obj_shablon')),
                ('shablon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task_shablon')),
            ],
            options={
                'verbose_name': 'Информация о задании',
                'verbose_name_plural': 'Информация о заданиях',
            },
        ),
        migrations.CreateModel(
            name='Individual_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата создания задания')),
                ('info_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.info_about_task')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name': 'Индивидуальное задание',
                'verbose_name_plural': 'Индивидуальные задания',
            },
        ),
        migrations.CreateModel(
            name='Comon_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата создания задания')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classes')),
                ('info_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.info_about_task')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name': 'Обычное задание',
                'verbose_name_plural': 'Обычные задания',
            },
        ),
    ]
