# Generated by Django 4.2.1 on 2023-06-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_obj_shablon_task_shablon_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_num',
            field=models.IntegerField(verbose_name='Номер класса'),
        ),
    ]
