# Generated by Django 4.2.1 on 2023-06-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_classes_class_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(default='SOME STRING', upload_to='')),
                ('uploaded_at', models.DateTimeField(default='', verbose_name='Дата создания задания')),
            ],
        ),
        migrations.AlterModelOptions(
            name='obj_shablon',
            options={'verbose_name': 'Шаблон объекта', 'verbose_name_plural': 'Шаблоны объектов'},
        ),
        migrations.AddField(
            model_name='comon_task',
            name='document',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='individual_task',
            name='document',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
