# Generated by Django 4.2.1 on 2023-06-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tasks_alter_obj_shablon_options_comon_task_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='answers',
            field=models.FileField(default='SOME STRING', upload_to=''),
        ),
        migrations.AlterField(
            model_name='info_about_task',
            name='obj_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.obj_shablon'),
        ),
    ]
